language: java
jdk:
  - openjdk8

branches: # CI를 어느 브랜치가 푸시될 때 수행할지 지정
  only:
    - master

# Travis CI 서버의 home
cache: #같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
  directories:
    - '$HOME/.me/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build'

#CI 실행 완료 시 메일로 알리기
notifications:
  email:
    recipients:
      - thdnjs5018@naver.com